import type { User, SwapRequest, Skill } from './types';

export const mockSkills: Skill[] = [
  { id: '1', name: 'Photoshop', description: 'Advanced photo editing and graphic design.' },
  { id: '2', name: 'Excel', description: 'Data analysis, pivot tables, and complex formulas.' },
  { id: '3', name: 'Guitar', description: 'Acoustic and electric guitar, from beginner chords to advanced solos.' },
  { id: '4', name: 'Yoga Instruction', description: 'Vinyasa flow and meditation guidance.' },
  { id: '5', name: 'Spanish Tutoring', description: 'Conversational Spanish for all levels.' },
  { id: '6', name: 'Creative Writing', description: 'Help with storytelling, character development, and prose.' },
  { id: '7', name: 'Public Speaking', description: 'Coaching on delivery, confidence, and presentation skills.' },
  { id: '8', name: 'Baking', description: 'Sourdough bread and pastry techniques.' },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Johnson',
    location: 'San Francisco, CA',
    avatarUrl: 'https://placehold.co/100x100.png',
    data_ai_hint: 'woman smiling',
    skillsOffered: [mockSkills[0], mockSkills[5]],
    skillsRequested: [mockSkills[2], mockSkills[4]],
    availability: 'Weekends, and weekday evenings after 6 PM.',
    profilePublic: true,
  },
  {
    id: 'user-2',
    name: 'Bob Williams',
    location: 'New York, NY',
    avatarUrl: 'https://placehold.co/100x100.png',
    data_ai_hint: 'man portrait',
    skillsOffered: [mockSkills[1], mockSkills[6]],
    skillsRequested: [mockSkills[3]],
    availability: 'Flexible, please message to coordinate.',
    profilePublic: true,
  },
  {
    id: 'user-3',
    name: 'Charlie Brown',
    location: 'Austin, TX',
    avatarUrl: 'https://placehold.co/100x100.png',
    data_ai_hint: 'person thinking',
    skillsOffered: [mockSkills[2], mockSkills[7]],
    skillsRequested: [mockSkills[0], mockSkills[1]],
    availability: 'Tuesday and Thursday mornings.',
    profilePublic: false,
  },
  {
    id: 'user-4',
    name: 'Diana Prince',
    location: 'Chicago, IL',
    avatarUrl: 'https://placehold.co/100x100.png',
    data_ai_hint: 'woman glasses',
    skillsOffered: [mockSkills[3], mockSkills[4]],
    skillsRequested: [mockSkills[5], mockSkills[6]],
    availability: 'Mondays and Wednesdays 10 AM - 4 PM.',
    profilePublic: true,
  },
];

export const mockSwaps: SwapRequest[] = [
  {
    id: 'swap-1',
    fromUser: { id: 'user-2', name: 'Bob Williams', avatarUrl: mockUsers[1].avatarUrl },
    toUser: { id: 'user-1', name: 'Alice Johnson', avatarUrl: mockUsers[0].avatarUrl },
    offeredSkill: mockSkills[1],
    requestedSkill: mockSkills[2],
    status: 'pending',
    message: 'Hey Alice! I can help with your Excel needs if you could teach me some guitar basics.',
    createdAt: '2 days ago',
  },
  {
    id: 'swap-2',
    fromUser: { id: 'user-4', name: 'Diana Prince', avatarUrl: mockUsers[3].avatarUrl },
    toUser: { id: 'user-1', name: 'Alice Johnson', avatarUrl: mockUsers[0].avatarUrl },
    offeredSkill: mockSkills[4],
    requestedSkill: mockSkills[5],
    status: 'pending',
    message: 'Hi, I saw you were looking for help with creative writing. I could help you in exchange for some Spanish lessons!',
    createdAt: '5 days ago',
  },
  {
    id: 'swap-3',
    fromUser: { id: 'user-1', name: 'Alice Johnson', avatarUrl: mockUsers[0].avatarUrl },
    toUser: { id: 'user-3', name: 'Charlie Brown', avatarUrl: mockUsers[2].avatarUrl },
    offeredSkill: mockSkills[0],
    requestedSkill: mockSkills[7],
    status: 'accepted',
    message: 'Let\'s do it! I\'d love to learn how to bake.',
    createdAt: '1 week ago',
  },
  {
    id: 'swap-4',
    fromUser: { id: 'user-3', name: 'Charlie Brown', avatarUrl: mockUsers[2].avatarUrl },
    toUser: { id: 'user-2', name: 'Bob Williams', avatarUrl: mockUsers[1].avatarUrl },
    offeredSkill: mockSkills[2],
    requestedSkill: mockSkills[6],
    status: 'rejected',
    message: 'Sorry, I don\'t have time for this right now.',
    createdAt: '2 weeks ago',
  },
  {
    id: 'swap-5',
    fromUser: { id: 'user-1', name: 'Alice Johnson', avatarUrl: mockUsers[0].avatarUrl },
    toUser: { id: 'user-4', name: 'Diana Prince', avatarUrl: mockUsers[3].avatarUrl },
    offeredSkill: mockSkills[5],
    requestedSkill: mockSkills[3],
    status: 'cancelled',
    message: 'Hey Diana, I actually found another yoga partner. Thanks though!',
    createdAt: '3 days ago',
  },
];
